services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - .env
    networks:
      - app-network

  adminer:
    image: adminer:latest
    restart: always
    container_name: adminer
    ports:
      - 8081:8080
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:


